#!groovy​
package com.github.jvanheesch.release1.alltests

import com.github.jvanheesch.HelperJava

@Library('test-joris')
import static com.github.jvanheesch.Helper.*

def pom

pipeline {
    agent {
        // TODO_JORIS: waar kan ik de namen van agents terugvinden?
        label 'master'
        HelperJava.someMethod()
    }

    options {
        disableConcurrentBuilds()
    }

    stages {
        stage('Slack') {
            steps {
                timestamps {
                    script {
                        slackSend channel: '#jenkins', color: 'good', message: 'Slack Message'
                    }
                }
            }
        }
        stage('Checkout') {
            steps {
                timestamps {
                    script {
                        echo 'shit1'
                        checkoutProject(this)
                        test(this)
                        pom = this.readMavenPom()
                    }
                }
            }
        }
        stage('Build') {
            steps {
                timestamps {
                    script {
                        echo 'shit2'
//                        mvn(this, "clean install -U -T 1C -DskipTests=true")
                        sh 'mvn clean install -U -T 1C -DskipTests=true'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                timestamps {
                    script {
                        echo 'shit3'
                        sh 'mvn ' + "verify " +
                                "-DskipUnitTests=false  " +
                                "-DskipIntegrationTests=false " +
                                "-Dconfig.plugin.failsafe.integrationTest.ignoreFailures=true " +
                                "-Dconfig.plugin.surefire.unitTest.ignoreFailures=true"
                    }
                }
            }
            post {
                always {
                    timestamps {
                        script {
                            echo 'shit4'
//                            publishTestResults(this)
                        }
                    }
                }
            }
        }
        stage('Notify') {
            steps {
                echo 'Sending notifications'
            }
            post {
                unstable {
                    script {
                        echo 'Echoing failure - TODO: integrate with slack.'
                    }
                }
            }
        }
    }
    post {
        failure {
            script {
                echo 'Echoing failure - TODO: integrate with slack.'
            }
        }
    }
}