#!groovy​
package com.github.jvanheesch.fromScratch

@Library('test-joris')
import static com.github.jvanheesch.GroovyConfig.slackChannel
import static com.github.jvanheesch.GroovyConfig.slackColor

def pom

pipeline {
    agent {
        label 'master'
    }

    options {
        disableConcurrentBuilds()
    }
    stages {
        stage('Slack') {
            steps {
                timestamps {
                    script {
                        slackSend channel: slackChannel, color: slackColor, message: 'Slack Message'
                    }
                }
            }
        }
    }
}