#!groovy​
package com.github.jvanheesch.declarative

pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                echo 'Exiting with code 1'
                sh "exit 1"
                echo 'This line should not be visible - script should have exited.'
            }
        }
    }
    post {
        failure {
            script {
                echo 'Echoing failure.'
            }
        }
    }
}